Stor_System/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Stor_System.Models
{
    public partial class Project
    {
        public Project()
        {
            ProjectEquipments = new HashSet<ProjectEquipment>();
        }

        public int ProjectId { get; set; }
        public int EmployeeRequesterId { get; set; }
        public int EmployeeDeliverId { get; set; }
        public string ProjectName { get; set; } = null!;
        public string? ProjectLocation { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string? ProjectDescription { get; set; }
        public string? ApproveStatus { get; set; }
        public string? ProjectStatus { get; set; }
        public string? InternalExternal { get; set; }
        public string? NotifivationSeen { get; set; }
        public DateTime? CreateDate { get; set; }
        public string? Active { get; set; }

        public virtual Employee EmployeeDeliver { get; set; } = null!;
        public virtual Employee EmployeeRequester { get; set; } = null!;
        public virtual ICollection<ProjectEquipment> ProjectEquipments { get; set; }


        [NotMapped]
        public int Quantity { get; set; }

        [NotMapped]
        public Dictionary<(string ProductName, string ModelName), int> ProductModelCounts { get; set; }
    }
}

Stor_System/Models/ProjectEquipment.cs
using System;
using System.Collections.Generic;

namespace Stor_System.Models
{
    public partial class ProjectEquipment
    {
        public int PeId { get; set; }
        public int ProjectId { get; set; }
        public int? ProDetailId { get; set; }

        public virtual ProductsDetail? ProDetail { get; set; }
        public virtual Project Project { get; set; } = null!;
    }
}

Stor_System/Models/ProjectViewModel.cs
namespace Stor_System.Models
{
    public class ProjectViewModel
    {
        public int ProjectId { get; set; }
        public int EmployeeRequesterId { get; set; }
        public int EmployeeDeliverId { get; set; }
        public string ProjectName { get; set; } = null!;
        public string? ProjectLocation { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string? ProjectDescription { get; set; }
        public string? ApproveStatus { get; set; }
        public string? ProjectStatus { get; set; }
        public string? NotifivationSeen { get; set; }
        public DateTime? CreateDate { get; set; }
        public string? Active { get; set; }
        public ICollection<ProductsModelViewModel> ProductsModels { get; set; } = new List<ProductsModelViewModel>();
    }

    public class ProductsModelViewModel
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; } = null!;
        public int ProductsDetailCount { get; set; }
    }
}

Stor_System/Controllers/App/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.NetworkInformation;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Stor_System.Models;

namespace Stor_System.Controllers.App
{
    public class ProjectsController : Controller
    {
        private readonly TawerStorContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;

        private readonly int Int_Role_ID;

        public ProjectsController(TawerStorContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;

            _httpContextAccessor = httpContextAccessor;
            var httpContext = _httpContextAccessor.HttpContext;

            Int_Role_ID = Convert.ToInt32(httpContext.Session.GetString("Role"));

        }
        //************************************************************* List *************************************************************
        // GET: Projects
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("Role") != "0")
            {
                string[] Request_Role_DTL = (HttpContext.Session.GetString("Request_Role_DTL")).Split(",");
                if (Request_Role_DTL[0] == "L")
                {
                    if (Request_Role_DTL[5] != " DI")
                    {
                        var AllUnSeenProject = await _context.Projects
                            .Include(PJ => PJ.EmployeeRequester)
                            .Include(PJ => PJ.EmployeeDeliver)
                            .Where(PJ => PJ.NotifivationSeen != "1")
                            .Where(PJ => PJ.ApproveStatus != "0")
                            .ToListAsync();
                        foreach (var project in AllUnSeenProject)
                        {
                            project.NotifivationSeen = "1";
                        }
                        await _context.SaveChangesAsync();
                    }



                    List<Project> PRJC = new List<Project>();

                    foreach (Project project in _context.Projects
                            .Include(b => b.ProjectEquipments).ThenInclude(pe => pe.ProDetail).ThenInclude(pe => pe.Product).ThenInclude(pe => pe.Brand)
                            .Include(b => b.ProjectEquipments).ThenInclude(pe => pe.ProDetail).ThenInclude(pe => pe.Product).ThenInclude(pe => pe.Category)
                            .Include(b => b.ProjectEquipments).ThenInclude(pe => pe.ProDetail).ThenInclude(pe => pe.Satuts)
                            .Where(m => m.Active == "1")

                            .OrderByDescending(PJ => PJ.ProjectId)
                            .ToList())
                    {
                        // Dictionary to store product names, model names, and their corresponding counts
                        var productModelCounts = project.ProjectEquipments
                            .GroupBy(pe => new { pe.ProDetail.Product.ProductName, pe.ProDetail.Product.ProductModel })
                            .ToDictionary(g => (g.Key.ProductName, g.Key.ProductModel), g => g.Count());

                        // Add project details to the PRJC list
                        PRJC.Add(new Project
                        {
                            ProjectId = project.ProjectId,
                            EmployeeRequesterId = project.EmployeeRequesterId,
                            EmployeeDeliverId = project.EmployeeDeliverId,
                            ProjectName = project.ProjectName,
                            ProjectLocation = project.ProjectLocation,
                            StartDate = project.StartDate,
                            EndDate = project.EndDate,

                            ProjectDescription = project.ProjectDescription,
                            ApproveStatus = project.ApproveStatus,
                            ProjectStatus = project.ProjectStatus,
                            NotifivationSeen = project.NotifivationSeen,
                            InternalExternal = project.InternalExternal,

                            CreateDate = project.CreateDate,
                            EmployeeDeliver = project.EmployeeDeliver,
                            EmployeeRequester = project.EmployeeRequester,

                            Quantity = project.ProjectEquipments.Count(),

                            // Assign the product and model counts to the new property
                            ProductModelCounts = productModelCounts
                        });
                    }

                    return View(PRJC);
                }
                else
                {
                    return RedirectToAction("Index", "LogIn");
                }
            }
            else
            {
                return RedirectToAction("Index", "LogIn");
            }


           
        }

        //************************************************************* List *************************************************************
        // GET: Projects
        public async Task<IActionResult> Archives()
        {
            if (HttpContext.Session.GetString("Role") != "0")
            {
                string[] Request_Role_DTL = (HttpContext.Session.GetString("Request_Role_DTL")).Split(",");
                if (Request_Role_DTL[4] == " A")
                {
                    List<Project> PRJC = new List<Project>();
                    foreach (Project project in _context.Projects
                            .Include(b => b.ProjectEquipments).ThenInclude(pe => pe.ProDetail).ThenInclude(pe => pe.Product).ThenInclude(pe => pe.Brand)
                            .Include(b => b.ProjectEquipments).ThenInclude(pe => pe.ProDetail).ThenInclude(pe => pe.Product).ThenInclude(pe => pe.Category)
                            .Include(b => b.ProjectEquipments).ThenInclude(pe => pe.ProDetail).ThenInclude(pe => pe.Satuts)
                            .Where(m => m.Active == "0")
                            .ToList())
                    {
                        // Dictionary to store product names, model names, and their corresponding counts
                        var productModelCounts = project.ProjectEquipments
                            .GroupBy(pe => new { pe.ProDetail.Product.ProductName, pe.ProDetail.Product.ProductModel })
                            .ToDictionary(g => (g.Key.ProductName, g.Key.ProductModel), g => g.Count());

                        // Add project details to the PRJC list
                        PRJC.Add(new Project
                        {
                            ProjectId = project.ProjectId,
                            EmployeeRequesterId = project.EmployeeRequesterId,
                            EmployeeDeliverId = project.EmployeeDeliverId,
                            ProjectName = project.ProjectName,
                            ProjectLocation = project.ProjectLocation,
                            StartDate = project.StartDate,
                            EndDate = project.EndDate,

                            ProjectDescription = project.ProjectDescription,
                            ApproveStatus = project.ApproveStatus,
                            ProjectStatus = project.ProjectStatus,
                            NotifivationSeen = project.NotifivationSeen,

                            CreateDate = project.CreateDate,
                            EmployeeDeliver = project.EmployeeDeliver,
                            EmployeeRequester = project.EmployeeRequester,

                            Quantity = project.ProjectEquipments.Count(),

                            // Assign the product and model counts to the new property
                            ProductModelCounts = productModelCounts
                        });
                    }

                    return View(PRJC);
                }
                else
                {
                    return RedirectToAction("Index", "LogIn");
                }
            }
            else
            {
                return RedirectToAction("Index", "LogIn");
            }

           
        }

        //************************************************************* Details ***********************************************************
        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Retrieve a single project based on the provided id and load all related data
            var project = await _context.Projects
                .Include(b => b.EmployeeDeliver)
                .Include(b => b.EmployeeRequester)
                .Include(b => b.ProjectEquipments)
                    .ThenInclude(pe => pe.ProDetail)
                    .ThenInclude(pe => pe.Product)
                    .ThenInclude(pe => pe.Brand)
                .Include(b => b.ProjectEquipments)
                    .ThenInclude(pe => pe.ProDetail)
                    .ThenInclude(pe => pe.Product)
                    .ThenInclude(pe => pe.Category)
                .Include(b => b.ProjectEquipments)
                    .ThenInclude(pe => pe.ProDetail)
                    .ThenInclude(pe => pe.Satuts)
                .Where(m => m.Active == "1" && m.ProjectId == id)
                .FirstOrDefaultAsync();

            if (project == null)
            {
                return NotFound();
            }

            // Dictionary to store product names, model names, and their corresponding counts
            var productModelCounts = project.ProjectEquipments
                .GroupBy(pe => new { pe.ProDetail.Product.ProductName, pe.ProDetail.Product.ProductModel })
                .ToDictionary(g => (g.Key.ProductName, g.Key.ProductModel), g => g.Count());

Stor_System/Views/Projects/Edit.cshtml
@model Stor_System.Models.Project
<style>
    .product-card {
        /* border: 1px solid #000; */
        padding: 10px;
        text-align: center;
        background-color: white;
        box-shadow: 0 -4px 11px 10px rgba(0, 0, 0, 0.1);
        border-radius: 5px
    }

        .product-card img {
            max-width: 100%;
            height: 77px;
            width: 109px;
            /*  float: right; */
        }

    .product-title {
        font-weight: bold;
        margin-top: 10px;
        height: 46px;
    }

    .product-details {
        margin-top: 5px;
    }

    .F_PH::placeholder {
        color: #c9c8c8; /* Adjust the placeholder color if needed */
    }

    .DDL {
        text-align: center
    }
</style>
<style>
    .container {
        display: flex;
        align-items: center;
    }

    button {
        width: 30px;
        height: 30px;
        font-size: 20px;
        text-align: center;
        cursor: pointer;
    }

    input[type="number"] {
        width: 60px;
        height: 30px;
        text-align: center;
        font-size: 16px;
        margin: 0 10px;
    }

    .quantity-controls {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 10px;
    }

    .decrease-btn, .increase-btn {
        width: 30px;
        height: 30px;
        font-size: 20px;
        text-align: center;
        cursor: pointer;
    }

    .basket {
        position: fixed;
        bottom: 10%;
        right: 2%;
        width: fit-content;
        text-align: center;
        padding: 10px;
        z-index: 1000;
        border-style: solid;
        border-radius: 5px;
        padding: 10px;
        background-color: #f2edf3;
    }

</style>






<form asp-controller="Projects" asp-action="Edit" method="post" id="Form1">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ProjectId" />
    <div class="container-fluid">
        <div class="row">
            <div class="col-8">
                <h2 style="font-size: 2.188rem;">Edit Request : @Model.ProjectName</h2>
            </div>
        </div>
        <div style="margin-bottom: 25px;">
            <a href="/Home/index" class="card-description" style="color: #b66dff;"><code>Dashboard</code> </a> /
            <a href="/Projects/index" class="card-description" style="color: #b66dff;"><code>Requests</code> </a> /
            <a href="/Projects/Edit/@Model.ProjectId" class="card-description" style="color: #b66dff;"><code>Edit Request : @Model.ProjectName</code> </a>
        </div>
        <div class="row" id="div1">
            <div class="col-lg-12 stretch-card">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="control-label">Project Name</label>
                                            <input asp-for="ProjectName" class="form-control" id="ProjectName_Input" />
                                            <span class="text-danger" id="ProjectName_Alert" style="display:none">* Project Name IS Required</span>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="control-label">Address</label>
                                            <input asp-for="ProjectLocation" class="form-control" id="ProjectLocation_Input" />
                                            <span class="text-danger" id="ProjectLocation_Alert" style="display:none">* Address IS Required</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="control-label">Start Date</label>
                                            <input asp-for="StartDate" class="form-control" type="date" id="StartDate_Input" />
                                            <span class="text-danger" id="StartDate_Alert" style="display:none">* Start Date IS Required</span>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="control-label">End Date</label>
                                            <input asp-for="EndDate" class="form-control" type="date" id="EndDate_Input" />
                                            <span class="text-danger" id="EndDate_Alert" style="display:none">* End Date IS Required</span>
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <div class="form-group">
                                            <label class="control-label">Project Status</label>
                                            <select asp-for="ProjectStatus" id="projectStatus" class="form-control">
                                                <option value="1">..... Select Status .....</option>
                                                <option value="2">On Progress</option>
                                                <option value="3">Out Of Stor</option>
                                                <option value="4">Finish</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-4" id="outOfStorDiv" style="display: none;">
                                        <div class="form-group">
                                            <label class="control-label">Delivered By</label>
                                            @Html.DropDownList("EmployeeId", null, "...... Select Employee ......", htmlAttributes: new { @class = "form-control", id = "EmployeeId"})
                                            <span class="text-danger" id="EmployeeId_Alert" style="display:none">* Employee IS Required</span>
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <div class="form-group">
                                            <label class="control-label">Internal / External</label><br>
                                            <div class="row" style="border-style: solid; border-width: thin; border-color: #ced4da; width: 100%; margin-left: 0%; padding: 6px; border-radius: 4px;">
                                                <div class="col-lg-6">
                                                    <input type="radio" id="Internal" name="InternalExternal" value="1" style="width:15px;height:20px;">
                                                    <label for="project1">Internal</label>
                                                </div>
                                                <div class="col-lg-6">
                                                    <input type="radio" id="External" name="InternalExternal" value="2" style="width:15px;height:20px;">
                                                    <label for="project2">External</label>
                                                </div>
                                            </div>
                                            <input type="hidden" id="InternalExternalText" asp-for="InternalExternal" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label class="control-label">Description</label>
                                            <textarea asp-for="ProjectDescription" class="form-control" style="height: 195px;"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>





                        <div style="display:none">
                            <input asp-for="EmployeeRequesterId" class="form-control" />
                            <input asp-for="EmployeeDeliverId" class="form-control" id="Emp_Id" />
                            <input asp-for="ApproveStatus" class="form-control" />
                            <input asp-for="Active" class="form-control" />
                        </div>




                        <div class="row">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <input type="button" value="Save" class="btn btn-primary" id="logProductIds" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>













<script src="~/js/signalr.js"></script>
<script src="~/js/notification.js" asp-append-version="true"></script>
<script src="~/js/signalr.js"></script>
<script src="~/js/signalr.min.js"></script>
<script src="~/js/site.js"></script>
<script src="~/js/userscount.js"></script>
<script src="~/js/notification.js"></script>


<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="~/js/project.js"></script>
<script>

    $(document).ready(function () {
        $('#EmployeeId').change(function () {
            var selectedValue = $(this).val();
            $('#Emp_Id').val(selectedValue);
        });
    });


    window.onload = function () {
        var internalExternalText = document.getElementById("InternalExternalText").value;

        if (internalExternalText === "1") {
            document.getElementById("Internal").checked = true;
        } else if (internalExternalText === "2") {
            document.getElementById("External").checked = true;
        }
    };


    document.querySelectorAll('input[name="InternalExternal"]').forEach(radio => {
        radio.addEventListener('change', function () {
            if (this.checked) {
                document.getElementById('InternalExternalText').value = this.value;
            }
        });
    });
</script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#projectStatus').change(function () {
            var selectedValue = $(this).val();
            if (selectedValue == '3') {
                $('#outOfStorDiv').show();
            } else {
                $('#outOfStorDiv').hide();
            }
        });
    });
</script>


































@* @model Stor_System.Models.Project

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProjectId" />
            
           
            
           
           
            



           
          
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

 *@

Stor_System/Views/Projects/ProjectEquipment.cshtml
@model IEnumerable<Stor_System.Models.ProductsModel>



<style>
    .product-card {
        border: 2px solid;
        padding: 10px;
        text-align: center;
        border-radius: 5px
    }

        .product-card img {
            max-width: 100%;
            height: 77px;
            width: 109px;
            /*  float: right; */
        }

    .product-title {
        font-weight: bold;
        margin-top: 10px;
        height: 46px;
    }

    .product-details {
        margin-top: 5px;
    }

    .F_PH::placeholder {
        color: #c9c8c8; /* Adjust the placeholder color if needed */
    }

    .DDL {
        text-align: center
    }
</style>
<style>
    .container {
        display: flex;
        align-items: center;
    }

    button {
        width: 30px;
        height: 30px;
        font-size: 20px;
        text-align: center;
        cursor: pointer;
    }

    input[type="number"] {
        width: 60px;
        height: 30px;
        text-align: center;
        font-size: 16px;
        margin: 0 10px;
    }

    .quantity-controls {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 10px;
    }

    .decrease-btn, .increase-btn {
        width: 30px;
        height: 30px;
        font-size: 20px;
        text-align: center;
        cursor: pointer;
    }

    .basket {
        position: fixed;
        bottom: 10%;
        right: 2%;
        width: fit-content;
        text-align: center;
        padding: 10px;
        z-index: 1000;
        border-style: solid;
        border-radius: 75px;
        padding: 10px;
        background-color: #f2edf3;
        border-color: #5190d5;
    }

</style>




<div class="container-fluid">
    <form asp-action="ProjectEquipment" asp-controller="Projects" method="post" id="Form1">
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="row justify-content-center text-center">
                <div class="col-lg-3" style="margin-bottom:15px">
                    @Html.DropDownList("CategoryId", null, "...... Select Category ......", htmlAttributes: new { @class = "form-control mx-auto DDL", id = "CategoryId"})
                </div>
                <div class="col-lg-3" style="margin-bottom:15px">
                    @Html.DropDownList("BrandId", null, "...... Select Brand ......", htmlAttributes: new { @class = "form-control mx-auto DDL" , id = "BrandId"})
                </div>
                <div class="col-lg-4" style="margin-bottom:15px">
                    <input type="text" placeholder="Search By Name" class="form-control mx-auto F_PH" />
                </div>
            </div>
        </div>
    </div>

    <div class="row" id="productContainer">
        @foreach (var item in Model)
        {
                string backgroundColor = item.QStatus > 0 ? "#ffffff" : item.QStatus <= 0 ? "#ffefef" : "#ffefef";
                string BorderColor = item.QStatus > 0 ? "#2cb12c" : item.QStatus <= 0 ? "#b31c1c" : "#b31c1c";

                <div class="col-lg-3 product-card-container" data-brand="@item.BrandId" data-category="@item.CategoryId" style="margin-bottom: 15px;">
                    <div class="product-card" style="background-color:@backgroundColor; border-color:@BorderColor">
                    <div class="row">
                        <div style="flex: 0 0 25%; max-width: 25%;"></div>
                        <div style="flex: 0 0 50%; max-width: 50%;">
                            @if (item.ImagePath == "")
                            {
                                <img src="~/A_Stor_System/assets/images/Icons/Equipments.png" alt="Product Image">
                            }
                            else
                            {
                                <img src="~/a_stor_system/assets/images/products/@item.ImagePath" alt="Product Image">
                            }
                        </div>
                    </div>
                    <div class="row">
                        <div class="product-title"><h3 style="font-size:22px;">@item.ProductName</h3></div>
                        <div class="product-details">
                            <div>Quantity: <span>@item.Quantity</span> Units | Available: @item.QStatus - @item.ProductId</div>
                        </div>
                        <div class="quantity-controls">
                            <img id="decrease-@item.ProductId" src="~/A_Stor_System/assets/images/Icons/minus.png" alt="Product Image" style="width:25px; height:25px;cursor:pointer">
                            <input type="number" id="quantity-input-@item.ProductId" value="0" min="0" max="@item.QStatus" readonly class="form-control" />
                            <img id="increase-@item.ProductId" src="~/A_Stor_System/assets/images/Icons/plus.png" alt="Product Image" style="width:25px; height:25px;cursor:pointer">
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    
        <div id="logProductIds" class="basket">
            <img src="~/a_stor_system/assets/images/icons/send.png" width="40" style="padding:5px"/>
        </div>


        <input type="hidden" id="productIds" name="Produts_Id_List" /><br />
        <input type="hidden" id="quantities" name="Produts_Qu_List" />
    </form>
</div>



@* <script src="~/js/signalr.js"></script>
<script src="~/js/notification.js" asp-append-version="true"></script>
<script src="~/js/signalr.js"></script>
<script src="~/js/signalr.min.js"></script>
<script src="~/js/site.js"></script>
<script src="~/js/userscount.js"></script>
<script src="~/js/notification.js"></script >*@


<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="~/js/projectequipment.js"></script>