Stor_System/Controllers/App/ProductsDetailsNController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Security.Cryptography;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Stor_System.Models;

namespace Stor_System.Controllers.App
{
    public class ProductsDetailsNController : Controller
    {
        private readonly TawerStorContext _context;

        public ProductsDetailsNController(TawerStorContext context)
        {
            _context = context;
        }
        //*************************************************** List For All ***************************************************
        // GET: ProductsDetailsN
        public async Task<IActionResult> IndexAll()
        {

            if (HttpContext.Session.GetString("Role") != "0")
            {
                string[] Product_Role_DTL = (HttpContext.Session.GetString("Product_Role_DTL")).Split(",");
                if (Product_Role_DTL[0] == "L")
                {
                    dynamic mymodel = new ExpandoObject();

                    // Fetch ProductsDetails along with the current associated Project
                    mymodel.ProductsDetails = _context.ProductsDetails
                        .Where(PD => PD.Active == "1")
                        .Include(p => p.Inventory)
                        .Include(p => p.Satuts)
                        .Include(p => p.Product)
                        .Select(pd => new
                        {
                            ProductsDetail = pd,
                            CurrentProject = pd.ProjectEquipments
                                .Where(pe => pe.Project.StartDate <= DateTime.Now && pe.Project.EndDate >= DateTime.Now)
                                .Where(pe=>pe.Project.ProjectStatus=="3")
                                .Select(pe => new
                                {
                                    pe.Project.ProjectName,
                                    pe.Project.StartDate,
                                    pe.Project.EndDate
                                })
                                .FirstOrDefault(),
                            ProjectHistories = pd.ProjectEquipments
                                        .Select(pe => new
                                        {
                                            pe.Project.ProjectName,
                                            pe.Project.StartDate,
                                            pe.Project.EndDate,
                                            pe.Project.ProjectStatus
                                        }).ToList()
                        }).OrderByDescending(PD =>PD.ProductsDetail.Product.ProductId )
                        .ToList();

                    mymodel.Status = _context.Satuts.ToList();
                    return View(mymodel);

                }
                else
                {
                    return RedirectToAction("Index", "LogIn");
                }
            }
            else
            {
                return RedirectToAction("Index", "LogIn");
            }
        }

        //*************************************************** List For One Model ***************************************************
        // GET: ProductsDetailsN
        public async Task<IActionResult> Index(int id)
        {
            if (HttpContext.Session.GetString("Role") != "0")
            {
                string[] Product_Role_DTL = (HttpContext.Session.GetString("Product_Role_DTL")).Split(",");
                if (Product_Role_DTL[0] == "L")
                {
                    dynamic mymodel = new ExpandoObject();
                    mymodel.ProductsDetails = _context.ProductsDetails
                        .Where(PD => PD.Active == "1")
                        .Where(PD => PD.ProductId == id)
                        .Include(p => p.Inventory)
                        .Include(p => p.Satuts)
                        .Include(p => p.Product).Select(pd => new
                        {
                            ProductsDetail = pd,
                            CurrentProject = pd.ProjectEquipments
                                .Where(pe => pe.Project.StartDate <= DateTime.Now && pe.Project.EndDate >= DateTime.Now)
                                .Where(pe => pe.Project.ProjectStatus == "3")
                                .Select(pe => new
                                {
                                    pe.Project.ProjectName,
                                    pe.Project.StartDate,
                                    pe.Project.EndDate
                                })
                                .FirstOrDefault(),
                            ProjectHistories = pd.ProjectEquipments
                                        .Select(pe => new
                                        {
                                            pe.Project.ProjectName,
                                            pe.Project.StartDate,
                                            pe.Project.EndDate,
                                            pe.Project.ProjectStatus
                                        }).ToList()
                        })
                        .ToList();


                    mymodel.Status = _context.Satuts.ToList();

                    var Model_Name = _context.ProductsModels.Where(e => e.ProductId == id).Select(e => e.ProductName).FirstOrDefault();
                    ViewBag.Model_Name = Model_Name;

                    var Model_Id = id;
                    ViewBag.Model_Id = Model_Id;

                    return View(mymodel);
                }
                else
                {
                    return RedirectToAction("Index", "LogIn");
                }
            }
            else
            {
                return RedirectToAction("Index", "LogIn");
            }
        }

        //*************************************************** List Archive *******************************************
        public async Task<IActionResult> Archive()
        {
            if (HttpContext.Session.GetString("Role") != "0")
            {
                string[] Product_Role_DTL = (HttpContext.Session.GetString("Product_Role_DTL")).Split(",");
                if (Product_Role_DTL[4] == " A")
                {
                    dynamic mymodel = new ExpandoObject();
                    mymodel.ProductsDetails = _context.ProductsDetails.Where(PD => PD.Active == "0").Include(p => p.Inventory).Include(p => p.Satuts).Include(p => p.Product).ToList();

                    return View(mymodel);
                }
                else
                {
                    return RedirectToAction("Index", "LogIn");
                }
            }
            else
            {
                return RedirectToAction("Index", "LogIn");
            }
        }

        //*************************************************** Details ***************************************************
        // GET: ProductsDetailsN/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ProductsDetails == null)
            {
                return NotFound();
            }

            var productsDetail = await _context.ProductsDetails
                .Include(p => p.Inventory)
                .Include(p => p.Product)
                .Include(p => p.Satuts)
                .FirstOrDefaultAsync(m => m.ProDetailId == id);
            if (productsDetail == null)
            {
                return NotFound();
            }

            return View(productsDetail);
        }
     
        //*************************************************** Edit ***************************************************
        // GET: ProductsDetailsN/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (HttpContext.Session.GetString("Role") != "0")
            {
                string[] Product_Role_DTL = (HttpContext.Session.GetString("Product_Role_DTL")).Split(",");
                if (Product_Role_DTL[2] == " E")
                {
                    if (id == null || _context.ProductsDetails == null)
                    {
                        return NotFound();
                    }

                    var Model_Name = _context.ProductsDetails.Where(e => e.ProDetailId == id).Select(e => e.Product.ProductName).FirstOrDefault();
                    ViewBag.Model_Name = Model_Name;



                    var productsDetail = await _context.ProductsDetails.FindAsync(id);
                    if (productsDetail == null)
                    {
                        return NotFound();
                    }
                    ViewData["InventoryId"] = new SelectList(_context.Inventories, "InventoryId", "InventoryName", productsDetail.InventoryId);
                    ViewData["ProductId"] = new SelectList(_context.ProductsModels, "ProductId", "ProductName", productsDetail.ProductId);
                    ViewData["SatutsId"] = new SelectList(_context.Satuts, "SatutsId", "SatutsName", productsDetail.SatutsId);
                    return View(productsDetail);
                }
                else
                {
                    return RedirectToAction("Index", "LogIn");
                }
            }
            else
            {
                return RedirectToAction("Index", "LogIn");
            }

            
        }

        // POST: ProductsDetailsN/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int MID ,int id, [Bind("ProDetailId,ProductId,InventoryId,SatutsId,MovementId,MovementLocation,ProDetailBarcode,ProDetailDescription,Active")] ProductsDetail productsDetail)
        {

            if (id != productsDetail.ProDetailId)
            {
                return NotFound();
            }

Stor_System/Views/ProductsDetailsN/Index.cshtml
@using Stor_System;
@model dynamic
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string[] Product_Role_DTL = Accessor.HttpContext.Session.GetString("Product_Role_DTL").Split(",");
}

<style>
    .product-card {
        padding: 10px;
        text-align: center;
        background-color: white;
        box-shadow: 0 -4px 11px 10px rgba(0, 0, 0, 0.1);
        border-radius: 5px;
    }

        .product-card img {
            max-width: 100%;
            height: 100px;
            width: 185px;
            float: right;
        }

    .product-title {
        font-weight: bold;
        margin-top: 10px;
        height: 75px;
    }

    .product-details {
        margin-top: 5px;
    }

    .F_PH::placeholder {
        color: #c9c8c8;
    }

    .DDL {
        text-align: center;
    }

    .circle-container {
        display: flex;
        justify-content: space-between;
        width: 150px;
        margin: 0 auto;
    }

    .circle {
        width: 30px;
        height: 30px;
        border-radius: 50%;
        margin-inline: auto;
    }
</style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

<div class="container-fluid">

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-8">
                            <h2 style="font-size: 2.188rem;">Quantity Of Model : @ViewBag.Model_Name</h2>
                        </div>
                        <div class="col-3">
                            <a href="~/ProductsModels/index" style="float: right;"><i class="fa fa-arrow-left"></i>&nbsp; Back</a>
                        </div>
                    </div>

                    <div style="margin-bottom: 25px;">
                        <a href="/Home/index" class="card-description" style="color: #b66dff;"><code>Dashboard</code> </a> /
                        <a href="/ProductsModels/index" class="card-description" style="color: #b66dff;"><code>Products</code> </a> /
                        <a href="/ProductsDetailsN/index/@ViewBag.Model_Id" class="card-description" style="color: #b66dff;"><code>Quantity Of Model : @ViewBag.Model_Name</code> </a>
                    </div>
                    <hr />

                    <div class="container-fluid">
                        <div class="row" style="text-align: center;">
                            @foreach (Satut Satut in Model.Status)
                            {
                                <div style="display:inline-block; width: fit-content;">
                                    <div class="circle" style="background-color:@Satut.Color; cursor:pointer;" onclick="filterProducts('@Satut.SatutsId')"></div>
                                    <p>@Satut.SatutsName</p>
                                </div>
                            }
                            <div style="display:inline-block; width: fit-content;">
                                <div class="circle" style="background-color:grey; cursor:pointer;" onclick="filterProducts('all')"></div>
                                <p>Show All</p>
                            </div>
                            <div style="display:inline-block; width: fit-content;">
                                <input type="text" id="barcodeSearch" class="form-control" placeholder="Search by Barcode" onkeyup="searchByBarcode()" />
                            </div>
                        </div>
                    </div>

                    <div class="accordion" id="accordionPanelsStayOpenExample">
                        @foreach (var item in Model.ProductsDetails)
                        {
                            var productDetail = item.ProductsDetail;
                            var CurrentProject = item.CurrentProject;
                            var projectHistories = item.ProjectHistories;

                            <div class="accordion-item" data-status-id="@productDetail.Satuts.SatutsId" data-barcode="@productDetail.ProDetailBarcode">
                                <h2 class="accordion-header" id="panelsStayOpen-heading-@productDetail.ProDetailId">
                                    <button class="accordion-button collapsed" style="background-color:@productDetail.Satuts.Color" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse-@productDetail.ProDetailId" aria-expanded="false" aria-controls="panelsStayOpen-collapse-@productDetail.ProDetailId">
                                        <div class="row" style="width: 100%;">
                                            <div class="col-lg-2">
                                                <strong>BarCode : </strong><br>@productDetail.ProDetailBarcode
                                            </div>
                                            <div class="col-lg-2">
                                                <strong>Satuts : </strong><br>@productDetail.Satuts.SatutsName
                                            </div>
                                            <div class="col-lg-2">
                                                <strong>Inventory : </strong><br>@productDetail.Inventory.InventoryName
                                            </div>
                                            <div class="col-lg-4">
                                                <strong>Curret Location : </strong><br> @(item.CurrentProject?.ProjectName ?? "In Stor")
                                            </div>
                                            <div class="col-lg-2">
                                                @{
                                                    if (Product_Role_DTL[3] == " D")
                                                    {
                                                        <div style="flex: 0 0 50%; max-width: 50%;">
                                                            <a asp-controller="ProductsDetailsN" asp-action="Delete" asp-route-id="@productDetail.ProDetailId"> <img src="~/a_stor_system/assets/images/icons/delete.png" style="width:20px;height:20px;float: left;" /></a>
                                                        </div>
                                                    }

                                                    if (Product_Role_DTL[2] == " E")
                                                    {
                                                        <div style="flex: 0 0 50%; max-width: 50%;">
                                                            <a asp-controller="ProductsDetailsN" asp-action="Edit" asp-route-id="@productDetail.ProDetailId"> <img src="~/a_stor_system/assets/images/icons/Edit.png" style="width:20px;height:20px;float: right;" /></a>
                                                        </div>
                                                    }
                                                }
                                            </div>
                                        </div>
                                    </button>
                                </h2>
                                <div id="panelsStayOpen-collapse-@productDetail.ProDetailId" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-heading-@productDetail.ProDetailId">
                                    <div class="accordion-body">
                                        <strong>Description :</strong>
                                        <br>
                                        <textarea style="height: 171px; width: 100%;  border-style: none;">@productDetail.ProDetailDescription</textarea>
                                        <hr>
                                        <div>
                                            <!-- Project History Table -->
                                            <strong>Project History</strong>
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                        <th>Project Name</th>
                                                        <th>Start Date</th>
                                                        <th>End Date</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach (var project in projectHistories)
                                                    {
                                                        <tr>
                                                            <td>@project.ProjectName</td>
                                                            <td>@project.StartDate?.ToString("yyyy-MM-dd")</td>
                                                            <td>@project.EndDate?.ToString("yyyy-MM-dd")</td>
                                                        </tr>
                                                    }
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function filterProducts(statusId) {
        var productItems = document.querySelectorAll('.accordion-item');
        productItems.forEach(function (item) {
            if (item.getAttribute('data-status-id') == statusId || statusId == "all") {
                item.style.display = "";
            } else {
                item.style.display = "none";
            }
        });
    }

    function searchByBarcode() {
        var input = document.getElementById('barcodeSearch').value.toLowerCase();
        var productItems = document.querySelectorAll('.accordion-item');
        productItems.forEach(function (item) {
            var barcode = item.getAttribute('data-barcode').toLowerCase();
            if (barcode.includes(input)) {
                item.style.display = "";
            } else {
                item.style.display = "none";
            }
        });
    }
</script>

Stor_System/Views/ProductsDetailsN/IndexAll.cshtml
@using Stor_System;
@model dynamic
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string[] Product_Role_DTL = Accessor.HttpContext.Session.GetString("Product_Role_DTL").Split(",");
}

<style>
    .product-card {
        padding: 10px;
        text-align: center;
        background-color: white;
        box-shadow: 0 -4px 11px 10px rgba(0, 0, 0, 0.1);
        border-radius: 5px;
    }

        .product-card img {
            max-width: 100%;
            height: 100px;
            width: 185px;
            float: right;
        }

    .product-title {
        font-weight: bold;
        margin-top: 10px;
        height: 75px;
    }

    .product-details {
        margin-top: 5px;
    }

    .F_PH::placeholder {
        color: #c9c8c8;
    }

    .DDL {
        text-align: center;
    }

    .circle-container {
        display: flex;
        justify-content: space-between;
        width: 150px;
        margin: 0 auto;
    }

    .circle {
        width: 30px;
        height: 30px;
        border-radius: 50%;
        margin-inline: auto;
    }
</style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

<div class="container-fluid">

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-8">
                            <h2 style="font-size: 2.188rem;">All Quantity </h2>
                        </div>
                        <div class="col-3">
                            <a href="~/Home/index" style="float: right;"><i class="fa fa-arrow-left"></i>&nbsp; Back</a>
                        </div>
                    </div>

                    <div style="margin-bottom: 25px;">
                        <a href="/Home/index" class="card-description" style="color: #b66dff;"><code>Dashboard</code> </a> /
                        <a href="/ProductsDetailsN/IndexAll" class="card-description" style="color: #b66dff;"><code>All Quantity </code> </a>
                    </div>
                    <hr />

                    <div class="container-fluid">
                        <div class="row" style="text-align: center;">
                            @foreach (Satut Satut in Model.Status)
                            {
                                <div style="display:inline-block; width: fit-content;">
                                    <div class="circle" style="background-color:@Satut.Color; cursor:pointer;" onclick="filterProducts('@Satut.SatutsId')"></div>
                                    <p>@Satut.SatutsName</p>
                                </div>
                            }
                            <div style="display:inline-block; width: fit-content;">
                                <div class="circle" style="background-color:grey; cursor:pointer;" onclick="filterProducts('all')"></div>
                                <p>Show All</p>
                            </div>
                            <div style="display:inline-block; width: fit-content;">
                                <input type="text" id="barcodeSearch" class="form-control" placeholder="Search by Barcode" onkeyup="searchByBarcode()" />
                            </div>
                        </div>
                    </div>

                    <div class="accordion" id="accordionPanelsStayOpenExample">
                        @foreach (var item in Model.ProductsDetails)
                        {
                            var productDetail = item.ProductsDetail;
                            var CurrentProject = item.CurrentProject;
                            var projectHistories = item.ProjectHistories;

                            <div class="accordion-item" data-status-id="@productDetail.Satuts.SatutsId" data-barcode="@productDetail.ProDetailBarcode">
                                <h2 class="accordion-header" id="panelsStayOpen-heading-@productDetail.ProDetailId">
                                    <button class="accordion-button collapsed" style="background-color:@productDetail.Satuts.Color" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse-@productDetail.ProDetailId" aria-expanded="false" aria-controls="panelsStayOpen-collapse-@productDetail.ProDetailId">
                                        <div class="row" style="width: 100%;">
                                            <div class="col-lg-2" style="border-style: solid;  padding: 5px;  text-align: center; border-radius: 5px;  border-color: gray;">
                                                <strong style="color: gray;">@productDetail.Product.ProductName</strong>
                                            </div>
                                            <div class="col-lg-2">
                                                <strong>BarCode : </strong><br>@productDetail.ProDetailBarcode
                                            </div>
                                            <div class="col-lg-2">
                                                <strong>Satuts : </strong><br>@productDetail.Satuts.SatutsName
                                            </div>
                                            <div class="col-lg-2">
                                                <strong>Inventory : </strong><br>@productDetail.Inventory.InventoryName
                                            </div>
                                            <div class="col-lg-2">
                                                <strong>Curret Location : </strong><br> @(item.CurrentProject?.ProjectName ?? "In Stor")
                                            </div>
                                            <div class="col-lg-2">
                                                @{
                                                    if (Product_Role_DTL[3] == " D")
                                                    {
                                                        <div style="flex: 0 0 50%; max-width: 50%;">
                                                            <a asp-controller="ProductsDetailsN" asp-action="Delete" asp-route-id="@productDetail.ProDetailId"> <img src="~/a_stor_system/assets/images/icons/delete.png" style="width:20px;height:20px;float: left;" /></a>
                                                        </div>
                                                    }

                                                    if (Product_Role_DTL[2] == " E")
                                                    {
                                                        <div style="flex: 0 0 50%; max-width: 50%;">
                                                            <a asp-controller="ProductsDetailsN" asp-action="Edit" asp-route-id="@productDetail.ProDetailId"> <img src="~/a_stor_system/assets/images/icons/Edit.png" style="width:20px;height:20px;float: right;" /></a>
                                                        </div>
                                                    }
                                                }
                                            </div>
                                        </div>
                                    </button>
                                </h2>
                                <div id="panelsStayOpen-collapse-@productDetail.ProDetailId" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-heading-@productDetail.ProDetailId">
                                    <div class="accordion-body">
                                        <strong>Description :</strong>
                                        <br>
                                        <textarea style="height: 171px; width: 100%;  border-style: none;">@productDetail.ProDetailDescription</textarea>
                                        <hr>
                                        <div>
                                            <!-- Project History Table -->
                                            <strong>Project History</strong>
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                        <th>Project Name</th>
                                                        <th>Start Date</th>
                                                        <th>End Date</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach (var project in projectHistories)
                                                    {
                                                        <tr>
                                                            <td>@project.ProjectName</td>
                                                            <td>@project.StartDate?.ToString("yyyy-MM-dd")</td>
                                                            <td>@project.EndDate?.ToString("yyyy-MM-dd")</td>
                                                        </tr>
                                                    }
                                                </tbody>
                                        </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function filterProducts(statusId) {
        var productItems = document.querySelectorAll('.accordion-item');
        productItems.forEach(function (item) {
            if (item.getAttribute('data-status-id') == statusId || statusId == "all") {
                item.style.display = "";
            } else {
                item.style.display = "none";
            }
        });
    }

    function searchByBarcode() {
        var input = document.getElementById('barcodeSearch').value.toLowerCase();
        var productItems = document.querySelectorAll('.accordion-item');
        productItems.forEach(function (item) {
            var barcode = item.getAttribute('data-barcode').toLowerCase();
            if (barcode.includes(input)) {
                item.style.display = "";
            } else {
                item.style.display = "none";
            }
        });
    }
</script>